server:
  port: 8081
spring:
  profiles:
    active: elapse_route
#---是添加配置文件的意思
---
spring:
  cloud:
    gateway:
      routes:
      - id: elapse_route
        uri: http://httpbin.org:80/get
        filters:
        - RequestTime=true
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
  profiles: elapse_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: http://httpbin.org:80/get
        predicates:
        - After=2020-01-20T17:42:47.789-07:00[America/Denver]
  profiles: after_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: head_route
        uri: http://httpbin.org:80/get
        predicates:
        -  Header=X-Request-Id, \d+
  profiles: head_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: add_head_route
        uri: http://httpbin.org/get
        filters:
        - AddRequestHeader=X-Request-Foo,Bar
        predicates:
        - After=2011-01-20T17:42:47.789-07:00[America/Denver]
  profiles: add_head_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: cookie_route
        uri: http://httpbin.org:80/get
        predicates:
        -  Cookie=name,lixp
  profiles: cookie_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: http://httpbin.org:80/get
        predicates:
        -  Host=**.lixp.com
  profiles: host_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: method_route
        uri: http://httpbin.org:80/get
        predicates:
        -  Method=GET
  profiles: method_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: hello_path_route
        uri: https://www.csdn.net
        predicates:
        - Path=/foo/{segment}
        filters:
        - RewritePath=/foo/(?<segment>.*), /$\{segment}
  profiles: hello_path_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: query_route
        uri: http://httpbin.org:80/get
        predicates:
        - Query=foo
  profiles: query_route

